version: '3.9'

services:
  dashboard-bff-dev:
    image: node:20-alpine
    container_name: dashboard-bff-nextjs-dev
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      # - NEXT_PUBLIC_API_URL=
      # - MEDIA_SERVICE_URL=http://localhost:8080
      # - USER_SERVICE_URL=http://user-service-express:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - backboard-network

networks:
  backboard-network:
    external: true

